version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(dep)"
    labels:
      - "dependencies"
      - "security"
      - "ci"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ci(dep)"
    labels:
      - "dependencies"
      - "security"
      - "ci"
