name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: yarn

    - name: Activate Yarn 3
      run: |
        corepack enable
        corepack prepare yarn@3.6.4 --activate
    - name: Install deps
      run: yarn install --immutable
    - name: Markdown lint
      run: yarn run mdlint

    - name: Lint
      run: yarn lint --max-warnings 0
    - name: Type check
      run: yarn tsc -b --noEmit
    - name: Run tests
      run: yarn test --coverage
    - name: Build plugin
      run: yarn build:fineco-it
    - name: Package plugin
      run: node scripts/package.js
    - name: Check bundle size
      run: yarn size
