name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: yarn

    - name: Enable Corepack
      run: corepack enable
    - name: Install deps
      run: yarn install --immutable --immutable-cache --check-cache

    - name: Run tests
      run: yarn test
